---
abstract: 'Serve static files with far-future expiry'
author:
  - 'Martyn Smith <martyn@dollyfish.net.nz>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-CDN
requires:
  MIME::Types: 1.28
  Moose: 2
  Path::Class: 0.24
  URI: 1.58
  perl: 5.010
version: 0.7
